"""initialized tables

Revision ID: d0796ceb5d87
Revises: 3779cddbebda
Create Date: 2023-10-06 08:55:29.762146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0796ceb5d87'
down_revision = '3779cddbebda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
